### list all messages in the system

GET http://localhost:3000/messages

### create a new mesage

POST  http://localhost:3000/messages
content-type: application/json

{
    "content": "This is the peace's message"
}

### Get  a particular message

GET http://localhost:3000/messages/150
